name: Test

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_course_definition:
    uses: ./.github/workflows/workflow-2.yml
